%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/anthonydugarte/Downloads/Instru/P2/matlab/ALL0001/F0001CH2.CSV
%
% Auto-generated by MATLAB on 02-Aug-2023 10:28:31

global R2 VLSUB;


%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [8, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "VarName4", "VarName5"];
opts.SelectedVariableNames = ["VarName4", "VarName5"];
opts.VariableTypes = ["string", "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "EmptyFieldRule", "auto");

% Import the data
VLSUB = readtable("ALL0002/F0003CH2.CSV", opts);

VLSUB = table2array(VLSUB);

VLSUB(:,1) = VLSUB(:,1) - VLSUB(1,1); % Desplazar el tiempo
% VLSUB(:,2) = VLSUB(:,2) / R2; % Dividir el voltaje del capacacitor entre la resistencia asociada

%% Clear temporary variables
clear opts