%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/anthonydugarte/Downloads/Instru/P2/matlab/ALL0001/F0001CH1.CSV
%
% Auto-generated by MATLAB on 01-Aug-2023 11:46:46

global VLSUB;

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

vlOffset = 59;

% Specify range and delimiter
opts.DataLines = [vlOffset , Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "VarName4", "VarName5"];
opts.SelectedVariableNames = ["VarName4", "VarName5"];
opts.VariableTypes = ["string", "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "EmptyFieldRule", "auto");

% Import the data
VLSUB = readtable("VL (Sub)/F0000CH1.CSV", opts);
VLSUB(:,1) = VLSUB(:,1) - VLSUB(1,1);

VLSUB = table2array(VLSUB);


%% Clear temporary variables
clear opts