%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/anthonydugarte/Downloads/Instru/P2/matlab/ALL0001/F0001CH1.CSV
%
% Auto-generated by MATLAB on 01-Aug-2023 11:46:46

global F0001CH1;

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [8, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "VarName4", "VarName5"];
opts.SelectedVariableNames = ["VarName4", "VarName5"];
opts.VariableTypes = ["string", "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "EmptyFieldRule", "auto");

% Import the data
F0001CH1 = readtable("ALL0000/F0000CH1.CSV", opts);
F0001CH1(:,1) = F0001CH1(:,1) - F0001CH1(1,1);

F0001CH1 = table2array(F0001CH1);


%% Clear temporary variables
clear opts